# Generated by Django 5.0.3 on 2024-04-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category_description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
