# Generated by Django 5.0.3 on 2024-04-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0002_item_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
